name: flutask
description: A TASK/PROJECT MANAGEMENT APP.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  progress_loading_button: ^1.1.6
  flutter_localizations:
    sdk: flutter
  http: ^1.0.0
  glassmorphism: ^3.0.0
  simple_circular_progress_bar: ^1.0.2
  easy_animated_tabbar: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # example:
  fonts:
    - family: Carter One
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
    - family: Kalam
      fonts:
        - asset: assets/fonts/Kalam-Bold.ttf
    - family: Signika Negative
      fonts:
        - asset: assets/fonts/SignikaNegative-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
